Repository WildCodeSchool/orleans-0218-cfa, pull requests merged in 2018-06, with the labels that each got.

#42 faq page static
  app/Resources/views/default/index.html.twig
  app/Resources/views/faq/faq.html.twig
  assets/scss/main.scss
  package-lock.json
  src/AppBundle/Controller/DefaultController.php
Labels: Reviewed by PO

#40 Get coordinates of UFA
  app/Resources/views/formation/new.html.twig
  app/Resources/views/ufa/index.html.twig
  app/Resources/views/ufa/new.html.twig
  app/Resources/views/ufa/show.html.twig
  composer.json
  composer.lock
  src/AppBundle/Controller/UfaController.php
  src/AppBundle/Entity/Ufa.php
  src/AppBundle/Form/UfaType.php
  src/AppBundle/Services/CoordinatesService.php
Labels: Reviewed by PO

#39 Fix footer
  app/Resources/views/base.html.twig
  assets/scss/main.scss
Labels: Correction Done, Reviewed by PO

#44 fix dev
  app/Resources/views/faq/faq.html.twig
  assets/scss/main.scss
  package-lock.json
Labels: Reviewed by PO

#45 Update README.md
  README.md
Labels: Reviewed by PO

#46 S3 us4 compteur num
  app/Resources/views/base.html.twig
  app/Resources/views/homepage/cfa.html.twig
  app/Resources/views/homepage/homepage.html.twig
  assets/js/app.js
  assets/scss/main.scss
  package-lock.json
  package.json
  webpack.config.js
Labels: Reviewed by PO

#47 Navbar
  app/Resources/views/base.html.twig
  assets/js/app.js
  web/images/Logo_Nav
Labels: Reviewed by PO

#49 ckeditor custom config
  app/config/config.yml
Labels: Reviewed by PO

#65 dev réparée
  app/Resources/views/base.html.twig
  package-lock.json
Labels: Reviewed by PO

#71 Us44 s4 events
  app/AppKernel.php
  app/Resources/views/event/edit.html.twig
  app/Resources/views/event/index.html.twig
  app/Resources/views/event/new.html.twig
  app/Resources/views/event/show.html.twig
  composer.json
  composer.lock
  package-lock.json
  src/AppBundle/Controller/EventController.php
  src/AppBundle/DataFixtures/AppFixtures.php
  src/AppBundle/Entity/Event.php
  src/AppBundle/Form/EventType.php
  src/AppBundle/Repository/EventRepository.php
  src/AppBundle/Tests/Controller/EventControllerTest.php
Labels: Correction Done, Reviewed by PO

#73 Dev
  app/AppKernel.php
  app/Resources/views/event/edit.html.twig
  app/Resources/views/event/index.html.twig
  app/Resources/views/event/new.html.twig
  app/Resources/views/event/show.html.twig
  composer.json
  composer.lock
  package-lock.json
  src/AppBundle/Controller/EventController.php
  src/AppBundle/DataFixtures/AppFixtures.php
  src/AppBundle/Entity/Event.php
  src/AppBundle/Form/EventType.php
  src/AppBundle/Repository/EventRepository.php
  src/AppBundle/Tests/Controller/EventControllerTest.php
Labels: Reviewed by PO

#72 S4 us12 apprenti
  app/Resources/views/apprenti/apprenti.html.twig
  assets/scss/main.scss
  src/AppBundle/Controller/DefaultController.php
Labels: Reviewed by PO

#75 création admin formation et routes
  app/Resources/views/formation/edit.html.twig
  app/Resources/views/formation/index.html.twig
  app/Resources/views/formation/new.html.twig
  app/Resources/views/formation/show.html.twig
  app/Resources/views/homepage/formation.html.twig
  app/Resources/views/homepage/homepage.html.twig
  app/Resources/views/layoutAdmin.html.twig
  assets/scss/main.scss
  src/AppBundle/Controller/AdminController/AdminController.php
  src/AppBundle/Controller/AdminController/AdminFormationController.php
  src/AppBundle/Controller/FormationController.php
Labels: Correction Done, Reviewed by PO

#79 fix
  app/Resources/views/apprenti/formation.twig
  src/AppBundle/Controller/DefaultController.php
Labels: Reviewed by PO

#77 Us3 s4 events vue dans homepage
  app/Resources/views/homepage/events.html.twig
  app/Resources/views/homepage/homepage.html.twig
  assets/scss/main.scss
  package-lock.json
  src/AppBundle/Controller/EventController.php
Labels: Correction Done, Reviewed by PO

#82 page statut apprenti
  app/Resources/views/apprenti/formation.html.twig
  app/Resources/views/apprenti/statut.html.twig
  app/Resources/views/homepage/events.html.twig
  assets/scss/main.scss
  src/AppBundle/Controller/DefaultController.php
Labels: Correction Done, Reviewed by PO

#81 cfa view
  app/Resources/views/base.html.twig
  app/Resources/views/cfa/edit.html.twig
  app/Resources/views/cfa/index.html.twig
  app/Resources/views/cfa/new.html.twig
  app/Resources/views/cfa/show.html.twig
  app/Resources/views/homepage/cfa.html.twig
  assets/scss/main.scss
  src/AppBundle/Controller/CfaController.php
  src/AppBundle/Entity/Cfa.php
  src/AppBundle/Form/CFAType.php
  src/AppBundle/Repository/CFARepository.php
  src/AppBundle/Tests/Controller/CFAControllerTest.php
Labels: Correction Done, Reviewed by PO

#86 mofif
  assets/scss/main.scss
Labels: Reviewed by PO

#87 Dev
  assets/scss/main.scss
Labels: Reviewed by PO

#92 Fix home page events scss
  app/Resources/views/homepage/events.html.twig
  assets/scss/main.scss
  phpunit.xml.dist
Labels: Reviewed by PO

#102 fix style apprenti formation
  app/Resources/views/apprenti/formation.html.twig
  assets/scss/main.scss
  web/images/apprenti.jpg
Labels: Reviewed by PO

#104 Us47 s5 events new
  app/Resources/views/event/new.html.twig
Labels: Reviewed by PO

#107 Index Events admin
  app/Resources/views/event/index.html.twig
Labels: Reviewed by PO

#109 Fix footer
  app/Resources/views/base.html.twig
Labels: Reviewed by PO

#108 Us48 s5 events update
  app/Resources/views/event/edit.html.twig
Labels: Reviewed by PO

#112 Dev
  app/Resources/views/apprenti/formation.html.twig
  app/Resources/views/base.html.twig
  app/Resources/views/event/edit.html.twig
  app/Resources/views/event/index.html.twig
  app/Resources/views/event/new.html.twig
  app/Resources/views/homepage/events.html.twig
  assets/scss/main.scss
  phpunit.xml.dist
  web/images/apprenti.jpg
Labels: Reviewed by PO

#111 Fix style faq
  app/Resources/views/apprenti/formation.html.twig
  app/Resources/views/faq/faq.html.twig
  assets/scss/main.scss
  web/images/faq.jpg
Labels: Conflicts Resolved, Reviewed by PO

#117 add standard plugin
  app/config/config.yml
Labels: Reviewed by PO

#119 Dev
  app/Resources/views/apprenti/formation.html.twig
  app/Resources/views/faq/faq.html.twig
  app/Resources/views/formation/formation.html.twig
  app/Resources/views/formation/index.html.twig
  app/Resources/views/homepage/formation.html.twig
  app/Resources/views/homepage/slider.html.twig
  app/config/config.yml
  assets/scss/main.scss
  src/AppBundle/Controller/AdminController/AdminFormationController.php
  src/AppBundle/Controller/FormationController.php
  web/images/background_formation.jpg
  web/images/faq.jpg
  web/images/its_tours_1.jpg
  web/images/its_tours_2.jpg
  web/images/mfr_1.jpg
  web/images/mfr_2.jpg
  web/images/mfr_4.jpg
  web/images/mfr_5.jpg
Labels: Reviewed by PO

#94 S4 us39 formation
  app/Resources/views/formation/public/formation.html.twig
  assets/scss/main.scss
  src/AppBundle/Controller/AdminController/AdminFormationController.php
  src/AppBundle/Controller/FormationController.php
  web/images/background_formation.jpg
  web/images/formation_back.jpg
  web/images/meeting_formation.jpeg
Labels: Correction Done, Reviewed by PO

#114 S5 us50 events vue publique
  app/Resources/views/event/edit.html.twig
  app/Resources/views/event/index.html.twig
  app/Resources/views/event/new.html.twig
  app/Resources/views/event/public/index.html.twig
  app/Resources/views/event/show.html.twig
  app/Resources/views/homepage/events.html.twig
  assets/scss/main.scss
  src/AppBundle/Controller/AdminController/AdminEventController.php
  src/AppBundle/Controller/EventController.php
  web/images/unsplash3.jpg
Labels: Reviewed by PO

#118 fix navbar
  app/Resources/views/_navbar.html.twig
  app/Resources/views/base.html.twig
  assets/scss/main.scss
  web/images/logo-navbar.png
Labels: Correction Done, Reviewed by PO

#120 fixture formation
  src/AppBundle/DataFixtures/FormationFixtures.php
Labels: Reviewed by PO

#123 check before dev2master
  assets/scss/main.scss
Labels: Reviewed by PO

#122 Fix style page
  app/Resources/views/apprenti/formation.html.twig
  app/Resources/views/faq/faq.html.twig
  assets/scss/main.scss
Labels: Reviewed by PO

#121 Fix apprenti statut
  app/Resources/views/apprenti/statut.html.twig
  assets/scss/main.scss
Labels: Conflicts Resolved, Correction Done, Reviewed by PO

#125 fix navbar burger
  app/Resources/views/_navbar.html.twig
Labels: Reviewed by PO

#126 Dev
  app/Resources/views/_navbar.html.twig
Labels: Reviewed by PO

#128 thumbnail apprenti homepage
  app/Resources/views/homepage/apprenti.html.twig
  app/Resources/views/homepage/homepage.html.twig
  app/Resources/views/homepage/slider.html.twig
  assets/scss/main.scss
  web/images/event_background_img.jpg
  web/images/formation_apprenti.jpg
  web/images/signature.jpg
  web/images/slider_1.jpg
  web/images/slider_2.jpg
  web/images/slider_3.jpg
  web/images/statut.jpg
Labels: Correction Done, Reviewed by PO

#138 S6 us21 show cart
  app/Resources/views/_navbar.html.twig
  app/Resources/views/ufa/public/map.html.twig
  assets/scss/main.scss
  src/AppBundle/Controller/MapController.php
  src/AppBundle/Entity/Formation.php
  src/AppBundle/Entity/Ufa.php
Labels: Conflicts Resolved, Correction Done, Reviewed by PO

#140 fix style sylvain homepage
  app/Resources/views/_footer.html.twig
  app/Resources/views/_navbar.html.twig
  app/Resources/views/base.html.twig
  app/Resources/views/event/public/index.html.twig
  app/Resources/views/homepage/cfa.html.twig
  app/Resources/views/homepage/events.html.twig
  app/Resources/views/homepage/homepage.html.twig
  app/Resources/views/homepage/slider.html.twig
  assets/images/background.png
  assets/images/footer.png
  assets/js/app.js
  assets/scss/main.scss
  package-lock.json
  webpack.config.js
Labels: Conflicts Resolved, Reviewed by PO

#142 Fix variable scss
  assets/images/apprenti.jpg
  assets/images/event_background_img.jpg
  assets/images/faq.jpg
  assets/images/formation_back.jpg
  assets/images/meeting_formation.jpeg
  assets/scss/main.scss
  web/images/Logo_Nav
Labels: Reviewed by PO

#143 Fix scss dev
  assets/scss/main.scss
  web/images/its_tours_2.jpg
  web/images/mfr_2.jpg
  web/images/mfr_5.jpg
Labels: Reviewed by PO

#144 Dev
  app/Resources/views/_footer.html.twig
  app/Resources/views/_navbar.html.twig
  app/Resources/views/base.html.twig
  app/Resources/views/event/public/index.html.twig
  app/Resources/views/homepage/apprenti.html.twig
  app/Resources/views/homepage/cfa.html.twig
  app/Resources/views/homepage/events.html.twig
  app/Resources/views/homepage/homepage.html.twig
  app/Resources/views/homepage/slider.html.twig
  app/Resources/views/ufa/public/map.html.twig
  assets/images/apprenti.jpg
  assets/images/background.png
  assets/images/event_background_img.jpg
  assets/images/faq.jpg
  assets/images/footer.png
  assets/images/formation_back.jpg
  assets/images/meeting_formation.jpeg
  assets/js/app.js
  assets/scss/main.scss
  package-lock.json
  src/AppBundle/Controller/MapController.php
  src/AppBundle/Entity/Formation.php
  src/AppBundle/Entity/Ufa.php
  web/images/Logo_Nav
  web/images/formation_apprenti.jpg
  web/images/its_tours_2.jpg
  web/images/mfr_2.jpg
  web/images/mfr_5.jpg
  web/images/signature.jpg
  web/images/statut.jpg
  webpack.config.js
Labels: Reviewed by PO

#141 S6 us5 formation accueil
  app/Resources/views/_navbar.html.twig
  app/Resources/views/formation/public/formation.html.twig
  app/Resources/views/homepage/formations.html.twig
  app/Resources/views/homepage/homepage.html.twig
  assets/scss/main.scss
  src/AppBundle/Controller/FormationController.php
  web/images/home_formation.jpg
Labels: Correction Done, Reviewed by PO

#147 S6 us41 admin edit formation
  app/Resources/views/formation/edit.html.twig
  app/Resources/views/formation/index.html.twig
Labels: Reviewed by PO

#152 S6 us40 admin show formation
  app/Resources/views/formation/show.html.twig
Labels: Reviewed by PO

#148 S6 us37 edit ufa
  app/Resources/views/ufa/edit.html.twig
  assets/scss/main.scss
  src/AppBundle/Form/UfaType.php
Labels: Correction Done, Reviewed by PO

#149 actualisation logo + liens navbar
  app/Resources/views/_navbar.html.twig
  web/images/logo_cfa.png
Labels: Correction Done, Reviewed by PO

#150 Us7 logo partenaires
  app/Resources/views/homepage/homepage.html.twig
  app/Resources/views/homepage/logoPartner.html.twig
  assets/scss/main.scss
  composer.json
  composer.lock
  src/AppBundle/Controller/PartnairController.php
  src/AppBundle/DataFixtures/PartnairFixtures.php
  web/images/Afcasa.jpg
  web/images/Logo CPNE-FP new.jpg
  web/images/Logo Croix-Rouge.png
  web/images/Logo DRDJSCS.jpg
  web/images/Logo Direccte.jpg
  web/images/Logo FNAPSS.jpg
  web/images/Logo MFR Azay.png
  web/images/Logo MFR.bmp
  web/images/Logo OETH.jpg
  web/images/Logo UNIFAF.jpg
  web/images/Logo_uniformation.jpg
  web/images/logo FIPHFP.jpg
  web/images/logo-region.jpg
  web/images/logo_CPNEF_quadri.jpg
Labels: Reviewed by PO

#155 S6 us53 formations dans ufa
  app/Resources/views/ufa/public/map.html.twig
  assets/scss/main.scss
Labels: Conflicts Resolved, Reviewed by PO

#156 S6 us53 accueil admin
  app/Resources/views/_navbarAdmin.html.twig
  app/Resources/views/apprenti/formation.html.twig
  app/Resources/views/apprenti/statut.html.twig
  app/Resources/views/base.html.twig
  app/Resources/views/cfa/edit.html.twig
  app/Resources/views/cfa/index.html.twig
  app/Resources/views/cfa/new.html.twig
  app/Resources/views/cfa/show.html.twig
  app/Resources/views/event/edit.html.twig
  app/Resources/views/event/index.html.twig
  app/Resources/views/event/new.html.twig
  app/Resources/views/event/public/index.html.twig
  app/Resources/views/event/show.html.twig
  app/Resources/views/faq/faq.html.twig
  app/Resources/views/formation/edit.html.twig
  app/Resources/views/formation/index.html.twig
  app/Resources/views/formation/new.html.twig
  app/Resources/views/formation/public/formation.html.twig
  app/Resources/views/formation/show.html.twig
  app/Resources/views/homepage/cfa.html.twig
  app/Resources/views/homepage/events.html.twig
  app/Resources/views/homepage/homepage.html.twig
  app/Resources/views/layout.html.twig
  app/Resources/views/layoutAdmin.html.twig
  app/Resources/views/partnair/edit.html.twig
  app/Resources/views/partnair/index.html.twig
  app/Resources/views/partnair/new.html.twig
  app/Resources/views/partnair/show.html.twig
  app/Resources/views/ufa/edit.html.twig
  app/Resources/views/ufa/index.html.twig
  app/Resources/views/ufa/new.html.twig
  app/Resources/views/ufa/public/map.html.twig
  app/Resources/views/ufa/show.html.twig
  assets/scss/admin.scss
  assets/scss/main.scss
  webpack.config.js
Labels: Correction Done, Reviewed by PO

#160 S6 fix formation
  app/Resources/views/formation/public/formation.html.twig
  app/Resources/views/homepage/formations.html.twig
  assets/scss/main.scss
Labels: Reviewed by PO

#161 fix thumnail
  app/Resources/views/homepage/apprenti.html.twig
  assets/images/formation_apprenti.jpg
  assets/images/signature.jpg
  assets/images/statut.jpg
  assets/scss/main.scss
Labels: Conflicts Resolved, Reviewed by PO

#162 Fix css accueil
  app/Resources/views/homepage/apprenti.html.twig
  app/Resources/views/homepage/events.html.twig
  app/Resources/views/layout.html.twig
  assets/scss/main.scss
Labels: Reviewed by PO

#163 Dev
  app/Resources/views/formation/public/formation.html.twig
  app/Resources/views/homepage/apprenti.html.twig
  app/Resources/views/homepage/events.html.twig
  app/Resources/views/homepage/formations.html.twig
  app/Resources/views/layout.html.twig
  assets/images/formation_apprenti.jpg
  assets/images/signature.jpg
  assets/images/statut.jpg
  assets/scss/main.scss
Labels: Reviewed by PO

#179 S7 us55 pointer color
  app/Resources/views/ufa/public/map.html.twig
  web/images/push-pin-red.png
  web/images/pushed-pin-blue.png
Labels: Reviewed by PO

#165 S7_US52_entity historicCfa + controller
  app/Resources/views/historiccfa/edit.html.twig
  app/Resources/views/historiccfa/index.html.twig
  app/Resources/views/historiccfa/new.html.twig
  app/Resources/views/historiccfa/show.html.twig
  src/AppBundle/Controller/AdminController/AdminHistoricCfaController.php
  src/AppBundle/Controller/HistoricCfaController.php
  src/AppBundle/Entity/Formation.php
  src/AppBundle/Entity/HistoricCfa.php
  src/AppBundle/Entity/Ufa.php
  src/AppBundle/Form/HistoricCfaType.php
  src/AppBundle/Repository/HistoricCfaRepository.php
  src/AppBundle/Tests/Controller/HistoricCfaControllerTest.php
Labels: Correction Done, Reviewed by PO

#185 List of ufas in formation
  app/Resources/views/formation/public/formation.html.twig
  app/Resources/views/ufa/public/map.html.twig
Labels: Reviewed by PO

#186 page statique embaucher un apprenti
  app/Resources/views/_navbar.html.twig
  app/Resources/views/employer/hireAnApprentice.html.twig
  assets/scss/main.scss
  src/AppBundle/Controller/DefaultController.php
Labels: Reviewed by PO

#187 Dev
  app/Resources/views/_navbar.html.twig
  app/Resources/views/apprenti/contrat.html.twig
  app/Resources/views/apprenti/statut.html.twig
  app/Resources/views/base.html.twig
  app/Resources/views/employer/hireAnApprentice.html.twig
  app/Resources/views/formation/public/formation.html.twig
  app/Resources/views/historiccfa/edit.html.twig
  app/Resources/views/historiccfa/index.html.twig
  app/Resources/views/historiccfa/new.html.twig
  app/Resources/views/historiccfa/show.html.twig
  app/Resources/views/layout.html.twig
  app/Resources/views/layoutAdmin.html.twig
  app/Resources/views/ufa/public/map.html.twig
  assets/scss/main.scss
  src/AppBundle/Controller/AdminController/AdminHistoricCfaController.php
  src/AppBundle/Controller/DefaultController.php
  src/AppBundle/Controller/HistoricCfaController.php
  src/AppBundle/Entity/Formation.php
  src/AppBundle/Entity/HistoricCfa.php
  src/AppBundle/Entity/Ufa.php
  src/AppBundle/Form/HistoricCfaType.php
  src/AppBundle/Repository/HistoricCfaRepository.php
  src/AppBundle/Tests/Controller/HistoricCfaControllerTest.php
  web/images/push-pin-red.png
  web/images/pushed-pin-blue.png
Labels: Reviewed by PO

#188 fix list none et map
  app/Resources/views/formation/public/formation.html.twig
  app/Resources/views/ufa/public/map.html.twig
  assets/scss/main.scss
Labels: Reviewed by PO

#190 Dev
  app/Resources/views/formation/public/formation.html.twig
  app/Resources/views/ufa/public/map.html.twig
  assets/scss/main.scss
Labels: Reviewed by PO

#189 S7_US30 admin cfa List
  app/Resources/views/_navbarAdmin.html.twig
  app/Resources/views/cfa/index.html.twig
  app/Resources/views/cfa/show.html.twig
  src/AppBundle/Controller/AdminController/AdminCfaController.php
  src/AppBundle/Controller/CfaController.php
  src/AppBundle/Entity/Cfa.php
Labels: Reviewed by PO

#191 S7 us32 cfa update
  app/Resources/views/cfa/edit.html.twig
Labels: Reviewed by PO

#192 Fosuser
  app/Resources/FOSUserBundle/views/Profile/edit.html.twig
  app/Resources/FOSUserBundle/views/Profile/show.html.twig
  app/Resources/FOSUserBundle/views/Registration/confirmed.html.twig
  app/Resources/FOSUserBundle/views/Registration/register.html.twig
  app/Resources/FOSUserBundle/views/Security/login.html.twig
  app/config/config.yml
  app/config/routing_dev.yml
  app/config/security.yml
  app/config/services.yml
  assets/scss/main.scss
  src/AppBundle/Entity/User.php
  src/AppBundle/Form/RegistrationType.php
  src/AppBundle/Repository/UserRepository.php
Labels: Reviewed by PO

#194 Fix navbar admin
  app/Resources/views/_navbarAdmin.html.twig
  assets/scss/admin.scss
Labels: Correction Done, Reviewed by PO

#195 Us 17 principe apprentissage
  app/Resources/views/_navbar.html.twig
  app/Resources/views/employer/hireAnApprentice.html.twig
  app/Resources/views/employer/learningCondition.html.twig
  assets/scss/main.scss
  src/AppBundle/Controller/DefaultController.php
  web/pdf/test.pdf
Labels: Reviewed by PO

#197 create timeline on historiccfa page
  app/Resources/views/historiccfa/historiccfa.html.twig
  assets/scss/timeline.scss
  src/AppBundle/Controller/HistoricCfaController.php
  src/AppBundle/Entity/HistoricCfa.php
  src/AppBundle/Repository/HistoricCfaRepository.php
  webpack.config.js
Labels: Reviewed by PO

#198 fix fosuser after access denied
  app/config/security.yml
  src/AppBundle/Controller/AdminController/AdminFormationController.php
Labels: Reviewed by PO

#201 S7 us56 re set coordinates
  app/Resources/views/ufa/edit.html.twig
  app/Resources/views/ufa/editCoord.html.twig
  src/AppBundle/Controller/UfaController.php
  src/AppBundle/Form/UfaCoordType.php
Labels: Reviewed by PO

#199 Dev
  app/Resources/FOSUserBundle/views/Profile/edit.html.twig
  app/Resources/FOSUserBundle/views/Profile/show.html.twig
  app/Resources/FOSUserBundle/views/Registration/confirmed.html.twig
  app/Resources/FOSUserBundle/views/Registration/register.html.twig
  app/Resources/FOSUserBundle/views/Security/login.html.twig
  app/Resources/views/_navbar.html.twig
  app/Resources/views/_navbarAdmin.html.twig
  app/Resources/views/cfa/edit.html.twig
  app/Resources/views/cfa/index.html.twig
  app/Resources/views/cfa/show.html.twig
  app/Resources/views/employer/hireAnApprentice.html.twig
  app/Resources/views/employer/learningCondition.html.twig
  app/Resources/views/ufa/edit.html.twig
  app/Resources/views/ufa/editCoord.html.twig
  app/config/config.yml
  app/config/routing_dev.yml
  app/config/security.yml
  app/config/services.yml
  assets/scss/admin.scss
  assets/scss/main.scss
  src/AppBundle/Controller/AdminController/AdminCfaController.php
  src/AppBundle/Controller/AdminController/AdminFormationController.php
  src/AppBundle/Controller/CfaController.php
  src/AppBundle/Controller/DefaultController.php
  src/AppBundle/Controller/UfaController.php
  src/AppBundle/Entity/Cfa.php
  src/AppBundle/Entity/User.php
  src/AppBundle/Form/RegistrationType.php
  src/AppBundle/Form/UfaCoordType.php
  src/AppBundle/Repository/UserRepository.php
  web/pdf/test.pdf
Labels: Reviewed by PO

#202 create timeline on historiccfa page
  app/Resources/views/historiccfa/historiccfa.html.twig
  assets/scss/timeline.scss
  src/AppBundle/Controller/HistoricCfaController.php
  src/AppBundle/Entity/HistoricCfa.php
  src/AppBundle/Repository/HistoricCfaRepository.php
  webpack.config.js
Labels: Reviewed by PO

#203 Us17 maitre apprentissage
  app/Resources/views/_navbar.html.twig
  app/Resources/views/employer/masterInstructor.html.twig
  assets/scss/main.scss
  src/AppBundle/Controller/DefaultController.php
Labels: Reviewed by PO

#211 Fosuser
  app/Resources/FOSUserBundle/views/Security/login.html.twig
  assets/scss/admin.scss
Labels: Reviewed by PO

#212 ajout section les aides
  app/Resources/views/employer/hireAnApprentice.html.twig
  assets/scss/main.scss
Labels: Reviewed by PO

#214 S7 us19 cfa
  app/Resources/views/_navbar.html.twig
  app/Resources/views/historiccfa/historiccfa.html.twig
  assets/scss/main.scss
  src/AppBundle/Controller/CfaController.php
  src/AppBundle/Controller/HistoricCfaController.php
  web/images/img_avatar1.png
  web/images/img_avatar6.png
Labels: Change Requested

#208 creation vue cotisations sociales
  app/Resources/views/_navbar.html.twig
  app/Resources/views/employer/socialSecurityContributions.html.twig
  assets/scss/main.scss
  src/AppBundle/Controller/DefaultController.php
Labels: Conflicts Resolved, Reviewed by PO

#213 S7 us46 formation upload
  app/AppKernel.php
  app/Resources/views/formation/index.html.twig
  app/Resources/views/formation/show.html.twig
  app/config/config.yml
  composer.lock
  src/AppBundle/Entity/Formation.php
  src/AppBundle/Form/FormationType.php
  web/uploads/5b34a4f15fcda_Compte rendu de réunion N°2.pdf
Labels: Correction Done, Reviewed by PO

#216 Fix cfapage
  app/Resources/views/historiccfa/historiccfa.html.twig
  assets/scss/main.scss
  assets/scss/timeline.scss
Labels: Correction Done, Question, Reviewed by PO

#215 Create CFA + design admin CFA
  app/Resources/views/cfa/edit.html.twig
  app/Resources/views/cfa/index.html.twig
  app/Resources/views/cfa/new.html.twig
  app/Resources/views/cfa/show.html.twig
  src/AppBundle/Entity/Cfa.php
  src/AppBundle/Form/CFAType.php
Labels: Correction Done, Reviewed by PO

#219 fix fichier pdf
  app/Resources/views/employer/learningCondition.html.twig
  web/pdf/contrat_d_apprentissage.pdf
Labels: Reviewed by PO

#221 fix navbar
  app/Resources/views/_navbar.html.twig
  app/Resources/views/apprenti/contrat.html.twig
  app/Resources/views/apprenti/formation.html.twig
  app/Resources/views/apprenti/statut.html.twig
  app/Resources/views/employer/hireAnApprentice.html.twig
  app/Resources/views/employer/learningCondition.html.twig
  app/Resources/views/employer/masterInstructor.html.twig
  app/Resources/views/employer/socialSecurityContributions.html.twig
  app/Resources/views/formation/public/formation.html.twig
  app/Resources/views/historiccfa/historiccfa.html.twig
  app/Resources/views/homepage/cfa.html.twig
  app/Resources/views/homepage/events.html.twig
  app/Resources/views/homepage/slider.html.twig
  app/Resources/views/layout.html.twig
  app/Resources/views/ufa/public/map.html.twig
  assets/js/app.js
  assets/scss/main.scss
Labels: Reviewed by PO

#222 ajout section employeurs homepage
  app/Resources/views/homepage/employer.html.twig
  app/Resources/views/homepage/homepage.html.twig
  assets/scss/main.scss
  web/images/employeurs_poignée_main.jpg
Labels: Reviewed by PO

#218 Dev
  .travis.yml
  app/AppKernel.php
  app/Resources/FOSUserBundle/views/Security/login.html.twig
  app/Resources/views/_navbar.html.twig
  app/Resources/views/_navbarAdmin.html.twig
  app/Resources/views/apprenti/contrat.html.twig
  app/Resources/views/apprenti/formation.html.twig
  app/Resources/views/apprenti/statut.html.twig
  app/Resources/views/cfa/edit.html.twig
  app/Resources/views/cfa/index.html.twig
  app/Resources/views/cfa/new.html.twig
  app/Resources/views/cfa/show.html.twig
  app/Resources/views/employer/hireAnApprentice.html.twig
  app/Resources/views/employer/learningCondition.html.twig
  app/Resources/views/employer/masterInstructor.html.twig
  app/Resources/views/employer/socialSecurityContributions.html.twig
  app/Resources/views/event/index.html.twig
  app/Resources/views/event/new.html.twig
  app/Resources/views/formation/index.html.twig
  app/Resources/views/formation/new.html.twig
  app/Resources/views/formation/public/formation.html.twig
  app/Resources/views/formation/show.html.twig
  app/Resources/views/historiccfa/historiccfa.html.twig
  app/Resources/views/homepage/cfa.html.twig
  app/Resources/views/homepage/employer.html.twig
  app/Resources/views/homepage/events.html.twig
  app/Resources/views/homepage/homepage.html.twig
  app/Resources/views/homepage/slider.html.twig
  app/Resources/views/layout.html.twig
  app/Resources/views/ufa/index.html.twig
  app/Resources/views/ufa/new.html.twig
  app/Resources/views/ufa/public/map.html.twig
  app/config/config.yml
  app/config/security.yml
  assets/js/app.js
  assets/scss/admin.scss
  assets/scss/main.scss
  assets/scss/timeline.scss
  composer.lock
  phpunit.xml.dist
  src/AppBundle/Controller/CfaController.php
  src/AppBundle/Controller/DefaultController.php
  src/AppBundle/Controller/HistoricCfaController.php
  src/AppBundle/Entity/Cfa.php
  src/AppBundle/Entity/Formation.php
  src/AppBundle/Form/CFAType.php
  src/AppBundle/Form/FormationType.php
  tests/AppBundle/Controller/DefaultControllerTest.php
  web/images/employeurs_poignée_main.jpg
  web/images/img_avatar1.png
  web/images/img_avatar6.png
  web/pdf/contrat_d_apprentissage.pdf
  web/uploads/5b34a4f15fcda_Compte rendu de réunion N°2.pdf
Labels: Correction Done, Reviewed by PO

#224 Dev
  app/Resources/views/homepage/formations.html.twig
  assets/scss/main.scss
  web/images/home_formation.jpg
  web/uploads/compte-rendu.pdf
Labels: Reviewed by PO
