Repository WildCodeSchool/orleans-0218-cfa, pull requests merged in 2018-07, with the labels that each got.

#233 Fix style section employeurs homepage
  app/Resources/views/homepage/employer.html.twig
  assets/scss/main.scss
  web/images/employeurs_poignée_main.jpg
Labels: Correction Done, Reviewed by PO

#235 Fix slider logo
  app/Resources/views/homepage/logoPartner.html.twig
  assets/scss/main.scss
Labels: Reviewed by PO

#238 Dev
  app/Resources/views/_navbar.html.twig
  app/Resources/views/formation/public/formation.html.twig
  app/Resources/views/homepage/cfa.html.twig
  app/Resources/views/homepage/employer.html.twig
  app/Resources/views/homepage/logoPartner.html.twig
  app/Resources/views/layout.html.twig
  app/Resources/views/layoutAdmin.html.twig
  app/Resources/views/partnair/edit.html.twig
  app/Resources/views/partnair/index.html.twig
  app/Resources/views/partnair/new.html.twig
  app/Resources/views/partnair/show.html.twig
  app/Resources/views/ufa/public/map.html.twig
  assets/scss/main.scss
  src/AppBundle/Controller/MapController.php
  web/images/IFSI_Façade.jpg
  web/images/employeurs_poignée_main.jpg
  web/images/meeting_formation.jpeg
Labels: Reviewed by PO

#240 Fix responsive maitre apprentissage
  app/Resources/views/employer/masterInstructor.html.twig
  assets/scss/main.scss
Labels: Reviewed by PO

#239 fix upload edit
  src/AppBundle/Entity/Formation.php
  src/AppBundle/Form/FormationType.php
  web/uploads/5b34a4f15fcda_Compte rendu de réunion N°2.pdf
  web/uploads/compte-rendu.pdf
Labels: Correction Done, Reviewed by PO

#243 fix marge mobile
  app/Resources/views/employer/learningCondition.html.twig
Labels: Reviewed by PO

#241 fix event cards and admin index sort
  app/Resources/views/event/index.html.twig
  app/Resources/views/homepage/events.html.twig
  assets/scss/main.scss
  src/AppBundle/Controller/AdminController/AdminEventController.php
  web/images/notebooks.jpg
Labels: Correction Done, Reviewed by PO

#244 Fix responsive employeur cotisations
  app/Resources/views/employer/socialSecurityContributions.html.twig
  assets/scss/main.scss
Labels: Conflicts Resolved, Reviewed by PO

#260 fix style admin ufa
  app/Resources/views/ufa/show.html.twig
Labels: Reviewed by PO

#247 add cards
  app/Resources/views/homepage/employer.html.twig
  assets/images/calculette.jpg
  assets/images/employeurs_poignée_main.jpg
  assets/images/etudiants.jpg
  assets/images/livres.jpg
  assets/scss/main.scss
Labels: Correction Done

#248 Fix cfa page
  app/Resources/views/_navbar.html.twig
  app/Resources/views/apprenti/formation.html.twig
  app/Resources/views/historiccfa/historiccfa.html.twig
  assets/images/cfa.jpg
  assets/scss/main.scss
Labels: Conflicts Resolved, Reviewed by PO

#268 S8 us12 apprenti formation
  app/Resources/views/apprenti/formation.html.twig
  src/AppBundle/Controller/DefaultController.php
  src/AppBundle/Controller/HistoricCfaController.php
Labels: Reviewed by PO

#269 Fix text formation
  app/Resources/views/formation/public/formation.html.twig
  assets/scss/main.scss
  web/uploads/compte-rendu.pdf
Labels: Reviewed by PO

#270 Fix slider partnair
  app/Resources/views/homepage/logoPartner.html.twig
Labels: Reviewed by PO

#274 S8 us54 historiccfa admin new
  app/Resources/views/historiccfa/index.html.twig
  app/Resources/views/historiccfa/new.html.twig
  src/AppBundle/Controller/AdminController/AdminHistoricCfaController.php
  src/AppBundle/Form/HistoricCfaType.php
Labels: Reviewed by PO

#276 Fix route partenaire
  src/AppBundle/Controller/PartnairController.php
Labels: Reviewed by PO

#272 Fix image homepage
  app/Resources/views/_navbar.html.twig
  app/Resources/views/homepage/cfa.html.twig
  app/Resources/views/homepage/slider.html.twig
  assets/scss/main.scss
  web/images/mfr_2.jpg
Labels: Correction Done, Reviewed by PO

#277 ajout lien navbar admin de l'historique
  app/Resources/views/_navbarAdmin.html.twig
  src/AppBundle/Controller/AdminController/AdminHistoricCfaController.php
Labels: Conflicts Resolved, Reviewed by PO

#281 Fix bannieres employeurs
  app/Resources/views/employer/hireAnApprentice.html.twig
  app/Resources/views/employer/learningCondition.html.twig
  app/Resources/views/employer/socialSecurityContributions.html.twig
  assets/scss/main.scss
Labels: Reviewed by PO

#282 Modifier une histoire
  app/Resources/views/historiccfa/edit.html.twig
  app/Resources/views/historiccfa/index.html.twig
  app/Resources/views/historiccfa/show.html.twig
  src/AppBundle/Controller/AdminController/AdminHistoricCfaController.php
Labels: Reviewed by PO

#284 ajout methode pour creer une histoire
  src/AppBundle/Controller/HistoricCfaController.php
Labels: Conflicts Resolved, Reviewed by PO

#286 delete historic
  app/Resources/views/historiccfa/edit.html.twig
  app/Resources/views/historiccfa/index.html.twig
  app/Resources/views/historiccfa/show.html.twig
  src/AppBundle/Controller/AdminController/AdminHistoricCfaController.php
Labels: Reviewed by PO

#290 S8 us69 upload cfa
  app/Resources/views/cfa/show.html.twig
  app/config/config.yml
  src/AppBundle/Entity/Cfa.php
  src/AppBundle/Form/CFAType.php
Labels: Reviewed by PO

#291 add links and fix color
  app/Resources/views/homepage/events.html.twig
Labels: Reviewed by PO

#262 crud apprentissage
  app/Resources/views/_navbarAdmin.html.twig
  app/Resources/views/taxe/edit.html.twig
  app/Resources/views/taxe/index.html.twig
  app/Resources/views/taxe/new.html.twig
  app/Resources/views/taxe/show.html.twig
  src/AppBundle/Controller/TaxeController.php
  src/AppBundle/Entity/Taxe.php
  src/AppBundle/Form/TaxeType.php
  src/AppBundle/Repository/TaxeRepository.php
  src/AppBundle/Tests/Controller/TaxeControllerTest.php
Labels: Change Requested

#267 Us59 upload images partner
  app/Resources/views/homepage/logoPartner.html.twig
  app/Resources/views/partnair/edit.html.twig
  app/config/config.yml
  src/AppBundle/Controller/PartnairController.php
  src/AppBundle/Entity/Partnair.php
  src/AppBundle/Form/PartnairType.php
Labels: Correction Done, Reviewed by PO

#289 show historiccfa
  app/Resources/views/historiccfa/index.html.twig
  src/AppBundle/Controller/AdminController/AdminHistoricCfaController.php
Labels: Conflicts Resolved, Reviewed by PO

#292 Fix route admin en cfabloisadmin et redirect index after edit
  app/config/security.yml
  src/AppBundle/Controller/AdminController/AdminCfaController.php
  src/AppBundle/Controller/AdminController/AdminController.php
  src/AppBundle/Controller/AdminController/AdminEventController.php
  src/AppBundle/Controller/AdminController/AdminFormationController.php
  src/AppBundle/Controller/AdminController/AdminHistoricCfaController.php
  src/AppBundle/Controller/PartnairController.php
  src/AppBundle/Controller/UfaController.php
Labels: Reviewed by PO

#293 fixes
  app/Resources/views/historiccfa/historiccfa.html.twig
  src/AppBundle/Controller/AdminController/AdminHistoricCfaController.php
  src/AppBundle/Controller/HistoricCfaController.php
Labels: Correction Done, Reviewed by PO

#294 Fix routes
  src/AppBundle/Controller/AdminController/AdminHistoricCfaController.php
  src/AppBundle/Controller/TaxeController.php
Labels: Reviewed by PO

#302 Us61 taxe apprentissage index
  app/Resources/views/taxe/index.html.twig
Labels: Reviewed by PO

#303 Fix mise en page employeurs
  app/Resources/views/employer/hireAnApprentice.html.twig
  app/Resources/views/employer/learningCondition.html.twig
  app/Resources/views/employer/masterInstructor.html.twig
  app/Resources/views/employer/socialSecurityContributions.html.twig
Labels: Reviewed by PO

#308 S8 us70 vue taxe
  app/Resources/views/_navbar.html.twig
  app/Resources/views/_navbarAdmin.html.twig
  app/Resources/views/taxe/taxeApprentissage.html.twig
  assets/scss/main.scss
  src/AppBundle/Controller/AdminController/AdminTaxeController.php
  src/AppBundle/Controller/TaxeController.php
  web/images/background_taxe.jpg
Labels: Reviewed by PO

#310 fix devices
  app/Resources/views/base.html.twig
Labels: Reviewed by PO

#309 plenthy of fixes
  app/Resources/views/cfa/index.html.twig
  app/Resources/views/formation/index.html.twig
  app/Resources/views/historiccfa/index.html.twig
  app/Resources/views/partnair/edit.html.twig
  app/Resources/views/partnair/index.html.twig
  app/Resources/views/partnair/show.html.twig
  app/Resources/views/ufa/edit.html.twig
  src/AppBundle/Controller/AdminController/AdminHistoricCfaController.php
  src/AppBundle/Form/CFAType.php
Labels: Correction Done

#315 change spacing admin navbar
  app/Resources/views/_navbarAdmin.html.twig
Labels: Reviewed by PO

#318 telecharger le projet CFA
  app/Resources/views/employer/socialSecurityContributions.html.twig
  app/Resources/views/historiccfa/historiccfa.html.twig
  src/AppBundle/Controller/AdminController/AdminHistoricCfaController.php
Labels: Reviewed by PO

#319 fix navbar color
  assets/scss/main.scss
Labels: Reviewed by PO

#320 fix the Tax Create btn
  app/Resources/views/taxe/index.html.twig
Labels: Reviewed by PO

#321 fix timeline text area and word break
  assets/scss/main.scss
  src/AppBundle/Form/HistoricCfaType.php
Labels: Reviewed by PO

#313 fix police size
  assets/scss/main.scss
Labels: Conflicts Resolved, Reviewed by PO

#322 style page apprenti formation
  app/Resources/views/apprenti/formation.html.twig
  app/Resources/views/apprenti/statut.html.twig
Labels: Reviewed by PO

#323 fix dev Tax admin part
  app/Resources/views/taxe/edit.html.twig
  app/Resources/views/taxe/new.html.twig
  app/Resources/views/taxe/show.html.twig
  src/AppBundle/Controller/AdminController/AdminTaxeController.php
Labels: Reviewed by PO

#317 If in the formation view
  app/Resources/views/formation/public/formation.html.twig
Labels: Correction Done, Reviewed by PO

#324 Dev
  app/Resources/views/_navbar.html.twig
  app/Resources/views/_navbarAdmin.html.twig
  app/Resources/views/apprenti/contrat.html.twig
  app/Resources/views/apprenti/formation.html.twig
  app/Resources/views/apprenti/statut.html.twig
  app/Resources/views/base.html.twig
  app/Resources/views/cfa/index.html.twig
  app/Resources/views/employer/hireAnApprentice.html.twig
  app/Resources/views/employer/learningCondition.html.twig
  app/Resources/views/employer/masterInstructor.html.twig
  app/Resources/views/employer/socialSecurityContributions.html.twig
  app/Resources/views/formation/index.html.twig
  app/Resources/views/formation/public/formation.html.twig
  app/Resources/views/historiccfa/historiccfa.html.twig
  app/Resources/views/historiccfa/index.html.twig
  app/Resources/views/partnair/edit.html.twig
  app/Resources/views/partnair/index.html.twig
  app/Resources/views/partnair/show.html.twig
  app/Resources/views/taxe/edit.html.twig
  app/Resources/views/taxe/index.html.twig
  app/Resources/views/taxe/new.html.twig
  app/Resources/views/taxe/show.html.twig
  app/Resources/views/taxe/taxeApprentissage.html.twig
  app/Resources/views/ufa/edit.html.twig
  assets/scss/main.scss
  src/AppBundle/Controller/AdminController/AdminHistoricCfaController.php
  src/AppBundle/Controller/AdminController/AdminTaxeController.php
  src/AppBundle/Controller/TaxeController.php
  src/AppBundle/Form/CFAType.php
  src/AppBundle/Form/HistoricCfaType.php
  web/images/background_taxe.jpg
Labels: Reviewed by PO

#330 titre page qui sommes nous ? de CAF
  app/Resources/views/historiccfa/historiccfa.html.twig
Labels: Reviewed by PO

#331 titre UFA
  app/Resources/views/ufa/public/map.html.twig
Labels: Reviewed by PO

#332 fix gitignore pour le dossier upload
  .gitignore
  web/uploads/.gitkeep
Labels: Reviewed by PO

#333 ajout d'un lien externe vers une map pour checker les coords
  app/Resources/views/ufa/show.html.twig
Labels: Reviewed by PO

#338 Fix logo and bigtitle
  app/Resources/views/layout.html.twig
  assets/scss/main.scss
  web/images/logo_cfa.png
Labels: Reviewed by PO

#341 Fix role security
  app/config/security.yml
Labels: Correction Done, Reviewed by PO

#335 Fix formation
  app/Resources/views/formation/public/formation.html.twig
  assets/scss/main.scss
Labels: Correction Done

#343 Dev
  .gitignore
  app/Resources/views/formation/public/formation.html.twig
  app/Resources/views/historiccfa/historiccfa.html.twig
  app/Resources/views/layout.html.twig
  app/Resources/views/ufa/public/map.html.twig
  app/Resources/views/ufa/show.html.twig
  app/config/security.yml
  assets/scss/main.scss
  web/images/logo_cfa.png
  web/uploads/.gitkeep
Labels: Reviewed by PO

#342 style page signer un contrat
  app/Resources/views/apprenti/contrat.html.twig
  assets/scss/main.scss
Labels: Reviewed by PO

#344 Fix tables admin
  app/Resources/views/partnair/index.html.twig
  app/Resources/views/taxe/index.html.twig
Labels: Reviewed by PO

#345 Fix margin padding
  app/Resources/views/homepage/events.html.twig
  app/Resources/views/homepage/formations.html.twig
Labels: Reviewed by PO

#346 Fix favicon
  app/Resources/views/base.html.twig
  web/favicon.ico
  web/images/favicon.png
Labels: Reviewed by PO

#347 Fix Cards Homepage thanks Portugal
  app/Resources/views/homepage/events.html.twig
  assets/scss/main.scss
Labels: Reviewed by PO

#348 fix formation issue 339
  app/Resources/views/formation/public/formation.html.twig
  assets/scss/main.scss
Labels: Reviewed by PO

#349 fix style ufa
  app/Resources/views/ufa/public/map.html.twig
  assets/scss/main.scss
Labels: Reviewed by PO

#351 Fix style page employeur embaucher
  app/Resources/views/employer/hireAnApprentice.html.twig
  assets/scss/main.scss
Labels: Reviewed by PO

#354 fix coordinates Lat/Long
  app/Resources/views/ufa/public/map.html.twig
  src/AppBundle/Controller/UfaController.php
  src/AppBundle/Services/CoordinatesService.php
Labels: Reviewed by PO

#314 Fix chiffres cfa
  app/Resources/views/cfa/index.html.twig
  app/Resources/views/cfa/new.html.twig
  app/Resources/views/cfa/show.html.twig
  app/Resources/views/historiccfa/historiccfa.html.twig
  app/Resources/views/homepage/cfa.html.twig
  app/Resources/views/homepage/homepage.html.twig
  src/AppBundle/Controller/CfaController.php
  src/AppBundle/Controller/HistoricCfaController.php
  src/AppBundle/Entity/Cfa.php
  src/AppBundle/Form/CFAType.php
  web/uploads/logo-region-centre-val-de-loire.jpg
Labels: Conflicts Resolved

#350 fix issue 334 UFA
  app/Resources/views/ufa/index.html.twig
  app/Resources/views/ufa/public/map.html.twig
  assets/scss/main.scss
  src/AppBundle/Entity/Ufa.php
  src/AppBundle/Form/UfaType.php
Labels: Conflicts Resolved, Correction Done, Reviewed by PO

#353 Fix title pages
  app/Resources/views/apprenti/contrat.html.twig
  app/Resources/views/apprenti/formation.html.twig
  app/Resources/views/apprenti/statut.html.twig
  app/Resources/views/cfa/edit.html.twig
  app/Resources/views/cfa/index.html.twig
  app/Resources/views/cfa/new.html.twig
  app/Resources/views/cfa/show.html.twig
  app/Resources/views/employer/hireAnApprentice.html.twig
  app/Resources/views/employer/learningCondition.html.twig
  app/Resources/views/employer/masterInstructor.html.twig
  app/Resources/views/employer/socialSecurityContributions.html.twig
  app/Resources/views/event/edit.html.twig
  app/Resources/views/event/index.html.twig
  app/Resources/views/event/new.html.twig
  app/Resources/views/event/public/event.html.twig
  app/Resources/views/event/public/index.html.twig
  app/Resources/views/event/show.html.twig
  app/Resources/views/faq/faq.html.twig
  app/Resources/views/formation/edit.html.twig
  app/Resources/views/formation/index.html.twig
  app/Resources/views/formation/new.html.twig
  app/Resources/views/formation/public/formation.html.twig
  app/Resources/views/formation/show.html.twig
  app/Resources/views/historiccfa/edit.html.twig
  app/Resources/views/historiccfa/historiccfa.html.twig
  app/Resources/views/historiccfa/index.html.twig
  app/Resources/views/historiccfa/new.html.twig
  app/Resources/views/historiccfa/show.html.twig
  app/Resources/views/homepage/homepage.html.twig
  app/Resources/views/layout.html.twig
  app/Resources/views/partnair/edit.html.twig
  app/Resources/views/partnair/index.html.twig
  app/Resources/views/partnair/new.html.twig
  app/Resources/views/partnair/show.html.twig
  app/Resources/views/taxe/edit.html.twig
  app/Resources/views/taxe/index.html.twig
  app/Resources/views/taxe/new.html.twig
  app/Resources/views/taxe/show.html.twig
  app/Resources/views/taxe/taxeApprentissage.html.twig
  app/Resources/views/ufa/edit.html.twig
  app/Resources/views/ufa/editCoord.html.twig
  app/Resources/views/ufa/index.html.twig
  app/Resources/views/ufa/new.html.twig
  app/Resources/views/ufa/public/map.html.twig
  app/Resources/views/ufa/show.html.twig
Labels: Reviewed by PO

#355 Fix creation evenements
  app/Resources/views/event/public/event.html.twig
  app/Resources/views/event/public/index.html.twig
  assets/images/metisse-happy.jpg
  assets/scss/main.scss
  src/AppBundle/Controller/AdminController/AdminEventController.php
Labels: Correction Done, Reviewed by PO

#358 fix space between logos
  app/Resources/views/homepage/logoPartner.html.twig
Labels: Reviewed by PO

#359 +
  app/Resources/views/historiccfa/historiccfa.html.twig
  web/pdf/projet_cfa.pdf
Labels: Reviewed by PO

#362 fix W3C
  app/Resources/views/apprenti/formation.html.twig
  app/Resources/views/base.html.twig
  app/Resources/views/employer/socialSecurityContributions.html.twig
  app/Resources/views/homepage/formations.html.twig
  app/Resources/views/taxe/taxeApprentissage.html.twig
Labels: Reviewed by PO

#365 fix W3C pages de dev
  app/Resources/views/formation/public/formation.html.twig
  app/Resources/views/historiccfa/historiccfa.html.twig
  app/Resources/views/ufa/public/map.html.twig
Labels: Correction Done, Reviewed by PO

#357 Us bonus faq entité
  app/Resources/views/_footer.html.twig
  app/Resources/views/_navbarAdmin.html.twig
  app/Resources/views/faq/edit.html.twig
  app/Resources/views/faq/faq.html.twig
  app/Resources/views/faq/index.html.twig
  app/Resources/views/faq/new.html.twig
  app/Resources/views/faq/public/faq.html.twig
  app/Resources/views/faq/show.html.twig
  src/AppBundle/Controller/AdminController/AdminFaqController.php
  src/AppBundle/Controller/DefaultController.php
  src/AppBundle/Controller/FaqController.php
  src/AppBundle/Entity/Faq.php
  src/AppBundle/Form/FaqType.php
  src/AppBundle/Repository/FaqRepository.php
  src/AppBundle/Tests/Controller/FaqControllerTest.php
Labels: Reviewed by PO

#366 add view legales notices
  app/Resources/views/_footer.html.twig
  app/Resources/views/homepage/legalesNotices.html.twig
  src/AppBundle/Controller/DefaultController.php
Labels: Conflicts Resolved, Reviewed by PO

#367 Reponsive homepage
  app/Resources/views/_navbar.html.twig
  app/Resources/views/homepage/cfa.html.twig
  app/Resources/views/homepage/slider.html.twig
  app/Resources/views/layout.html.twig
  assets/scss/main.scss
Labels: Reviewed by PO

#369 Fix photo presidence
  app/Resources/views/historiccfa/historiccfa.html.twig
  assets/scss/main.scss
Labels: Conflicts Resolved, Reviewed by PO

#370 Logo admin
  app/Resources/views/_navbarAdmin.html.twig
Labels: Reviewed by PO

#371 many fixes
  app/Resources/views/_footer.html.twig
  app/Resources/views/_navbar.html.twig
  app/Resources/views/event/public/event.html.twig
  app/Resources/views/event/public/index.html.twig
  app/Resources/views/homepage/logoPartner.html.twig
  app/Resources/views/ufa/public/map.html.twig
  src/AppBundle/Controller/DefaultController.php
Labels: Reviewed by PO

#373 Fix liens interne
  app/Resources/views/employer/learningCondition.html.twig
  app/Resources/views/employer/socialSecurityContributions.html.twig
  web/pdf/Convention de formation v7 générique.pdf
  web/pdf/contrat_d_apprentissage.pdf
  web/pdf/test.pdf
Labels: Reviewed by PO

#374 Fix button event
  app/Resources/views/event/public/event.html.twig
  app/Resources/views/event/public/index.html.twig
Labels: Reviewed by PO

#377 fix UFA entity
  src/AppBundle/Entity/Ufa.php
Labels: Correction Done, Reviewed by PO

#380 Fix color events cards
  app/Resources/views/homepage/events.html.twig
Labels: Reviewed by PO

#382 Dev
  app/Resources/views/homepage/apprenti.html.twig
  app/Resources/views/homepage/cfa.html.twig
  app/Resources/views/homepage/employer.html.twig
  app/Resources/views/homepage/events.html.twig
  app/Resources/views/partnair/edit.html.twig
Labels: Reviewed by PO

#384 Dev
  app/Resources/views/homepage/logoPartner.html.twig
Labels: Reviewed by PO

#385 Fix size logo
  assets/scss/main.scss
Labels: Reviewed by PO

#386 Fix chiffre cfa
  app/Resources/views/homepage/cfa.html.twig
  app/Resources/views/ufa/public/map.html.twig
Labels: Reviewed by PO

#388 fix orthographe apprenti et qui sommes nous?
  app/Resources/views/apprenti/contrat.html.twig
  app/Resources/views/apprenti/statut.html.twig
  app/Resources/views/historiccfa/historiccfa.html.twig
  assets/scss/main.scss
Labels: Reviewed by PO

#389 Fix employeurs
  app/Resources/views/_navbar.html.twig
  app/Resources/views/employer/hireAnApprentice.html.twig
  app/Resources/views/employer/learningCondition.html.twig
  app/Resources/views/employer/masterInstructor.html.twig
  app/Resources/views/employer/socialSecurityContributions.html.twig
Labels: Correction Done, Reviewed by PO

#390 fixSortFormations
  src/AppBundle/Controller/FormationController.php
Labels: Reviewed by PO

#391 Dev
  app/Resources/views/_navbar.html.twig
  app/Resources/views/apprenti/contrat.html.twig
  app/Resources/views/apprenti/statut.html.twig
  app/Resources/views/employer/debriefingEmployers.html.twig
  app/Resources/views/employer/hireAnApprentice.html.twig
  app/Resources/views/employer/learningCondition.html.twig
  app/Resources/views/employer/masterInstructor.html.twig
  app/Resources/views/employer/socialSecurityContributions.html.twig
  app/Resources/views/historiccfa/historiccfa.html.twig
  app/Resources/views/homepage/cfa.html.twig
  app/Resources/views/homepage/legalesNotices.html.twig
  app/Resources/views/ufa/public/map.html.twig
  assets/scss/main.scss
  src/AppBundle/Controller/DefaultController.php
  src/AppBundle/Controller/FormationController.php
Labels: Reviewed by PO

#393 augmentation vitesse defilement carousel
  app/Resources/views/homepage/logoPartner.html.twig
  assets/scss/main.scss
Labels: Reviewed by PO

#394 fix: change police presidente letter
  app/Resources/views/historiccfa/historiccfa.html.twig
  assets/scss/main.scss
Labels: Reviewed by PO

#395 Fic couleur employeurs
  assets/scss/main.scss
Labels: Reviewed by PO

#397 Fix temoignage
  app/Resources/views/_navbar.html.twig
  app/Resources/views/employer/debriefingEmployers.html.twig
Labels: Reviewed by PO

#398 Fix slider
  app/Resources/views/homepage/slider.html.twig
  web/images/slider2.jpg
  web/images/slider3.jpg
Labels: Reviewed by PO

#400 Fix logo mac
  app/Resources/views/homepage/logoPartner.html.twig
  assets/scss/main.scss
Labels: Reviewed by PO

#401 2nd last f ix
  app/Resources/views/employer/debriefingEmployers.html.twig
  app/Resources/views/homepage/cfa.html.twig
  assets/scss/main.scss
  src/AppBundle/Entity/Cfa.php
  web/images/blois3.jpg
Labels: Reviewed by PO

#402 fix police
  app/Resources/views/apprenti/statut.html.twig
  app/Resources/views/employer/hireAnApprentice.html.twig
  package-lock.json
  web/pdf/Convention de formation v7 générique.pdf
Labels: Reviewed by PO

#403 Dev
  app/Resources/views/apprenti/statut.html.twig
  app/Resources/views/employer/debriefingEmployers.html.twig
  app/Resources/views/employer/hireAnApprentice.html.twig
  app/Resources/views/homepage/cfa.html.twig
  app/Resources/views/homepage/logoPartner.html.twig
  assets/scss/main.scss
  package-lock.json
  src/AppBundle/Entity/Cfa.php
  web/images/blois3.jpg
  web/pdf/Convention de formation v7 générique.pdf
Labels: Reviewed by PO

#404 last last fix
  app/Resources/views/homepage/employer.html.twig
Labels: Reviewed by PO

#405 Dev
  app/Resources/views/homepage/employer.html.twig
Labels: Reviewed by PO
