Repository WildCodeSchool/orleans-0218-cfa, pull requests merged in 2018-05, with the labels that each got.

#8 Dev
  .gitignore
  README.md
  app/AppKernel.php
  app/config/parameters.yml.dist
  composer.json
  composer.lock
Labels: Reviewed by PO

#14 Dev
  .gitignore
  assets/js/app.js
  assets/scss/main.scss
  package-lock.json
  package.json
  webpack.config.js
Labels: Reviewed by PO

#15 Fix config
  .gitignore
  app/config/config.yml
  app/config/routing.yml
Labels: Change Requested

#21 Dev
  .gitignore
  app/Resources/views/base.html.twig
  app/Resources/views/ufa/edit.html.twig
  app/Resources/views/ufa/index.html.twig
  app/Resources/views/ufa/new.html.twig
  app/Resources/views/ufa/show.html.twig
  app/config/config.yml
  app/config/parameters.yml.dist
  assets/scss/main.scss
  composer.json
  composer.lock
  src/AppBundle/Controller/UfaController.php
  src/AppBundle/Entity/Ufa.php
  src/AppBundle/Form/UfaType.php
  src/AppBundle/Repository/UfaRepository.php
  src/AppBundle/Tests/Controller/UfaControllerTest.php
Labels: Reviewed by PO

#29 S2 us8 footer
  .gitignore
  app/Resources/views/base.html.twig
  app/config/parameters.yml.dist
  assets/scss/main.scss
  package-lock.json
Labels: Reviewed by PO

#32 S3_US2_création du slider
  app/Resources/views/homepage/homepage.html.twig
  app/Resources/views/homepage/slider.html.twig
  assets/js/app.js
  assets/scss/main.scss
  package-lock.json
  package.json
  src/AppBundle/Controller/DefaultController.php
  web/images/its_tours_1.jpg
  web/images/mfr_1.jpg
  web/images/mfr_4.jpg
Labels: Correction Done

#38 Us 27 wysiwyg
  app/AppKernel.php
  composer.json
  composer.lock
  package-lock.json
  src/AppBundle/Form/FormationType.php
Labels: Reviewed by PO
